### ISSUE TITLE
Le serveur ne fonctionne qu'en sandbox

### ISSUE THREAD

**Issue by Jean-Serge** [derniercri/erlang-standard-backend#1]
Pour pouvoir utiliser ce fichier de conf, il faudrait changer l'adresse sur laquelle le serveur va écouter.

[Cette ligne](https://github.com/derniercri/erlang-standard-backend/blob/master/yaws.conf#L21) devrait être remplacée par `listen = 0.0.0.0`

**Comment by xvw** [comment]
done thanks
